name: first-job

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo "executing file read in same repo"
        ls -lrt | awk '{print $NF}' | sed -n 2p | xargs cat
    - name: Generate ascii art
      run: |
        sudo apt install cowsay -y
        cowsay -f elephant "I am a elephant of Tejas a paltu elephant" > elephant.txt
        cat elephant.txt

