name: first-job

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo "executing file read in same repo"
        ls -lrt | awk '{print $NF}' | sed -n 2p | xargs cat
    - name: Generate ascii art
      run: |
        cowsay -f dragon "I am a dragon of Tejas a paltu dragon" > dragon.txt
        cat dragon.txt

